---
run:
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dupl
    - gochecknoinits
    - goconst
    - gofmt
    - ineffassign
    - interfacer
    - misspell
    - structcheck
    - typecheck
    - varcheck
    # - errcheck
    # - gochecknoglobals
    # - gocritic
    # - gocyclo
    # - goimports
    # - golint
    # - gosec
    # - govet
    # - lll
    # - maligned
    # - megacheck
    # - nakedret
    # - prealloc
    # - scopelint
    # - unconvert
    # - unparam
issues:
  exclude:
    - .*_Ctype_security_context_t.*
