---
run:
  build-tags:
    - apparmor
    - ostree
    - seccomp
    - selinux
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # - gochecknoglobals
    # - gochecknoinits
    # - goconst
    # - gocritic
    # - gocyclo
    # - goimports
    # - golint
    # - gosec
    # - interfacer
    # - lll
    # - maligned
    # - misspell
    # - prealloc
    # - scopelint
    # - stylecheck
    # - unconvert
    # - unparam
