---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: buildah
upstream_tag_template: v{version}

specfile_path: rpm/buildah.spec

srpm_build_deps:
  - make

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Packit jobs failed. @containers/packit-build please check."
    targets:
      - epel-9-x86_64
      - epel-9-aarch64
      - epel-10-x86_64
      - epel-10-aarch64
    enable_net: true

  # Tests on RHEL 9 and RHEL 10 using internal Testing Farm ranch
  - job: tests
    trigger: pull_request
    use_internal_tf: true
    targets:
      - rhel-9-x86_64
      - rhel-10-x86_64
