---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  - job: tests
    trigger: pull_request
    skip_build: true
    use_internal_tf: true
    notifications: &packit_failure_notification
      failure_comment:
        message: "Packit jobs failed. @containers/packit-build please check."
    targets:
      epel-10-x86_64:
        distros: [RHEL-10.0-Nightly]
      epel-9-x86_64:
        distros: [RHEL-9.6.0-Nightly]
