branches:
  - master
  - auto
  - try

host:
  distro: fedora/26/atomic

required: true

tests:
  #  Let's create a self signed certificate and get it in the right places
  - hostname
  - ip a
  - ping -c 3 localhost
  - cat /etc/hostname
  - mkdir -p /home/travis/auth
  - openssl req -newkey rsa:4096 -nodes -sha256 -keyout /home/travis/auth/domain.key -x509 -days 2 -out /home/travis/auth/domain.crt -subj "/C=US/ST=Foo/L=Bar/O=Red Hat, Inc./CN=localhost"
  - cp /home/travis/auth/domain.crt /home/travis/auth/domain.cert
  - sudo mkdir -p /etc/docker/certs.d/docker.io/
  - sudo cp /home/travis/auth/domain.crt /etc/docker/certs.d/docker.io/ca.crt
  - sudo mkdir -p /etc/docker/certs.d/localhost:5000/
  - sudo cp /home/travis/auth/domain.crt /etc/docker/certs.d/localhost:5000/ca.crt
  - sudo cp /home/travis/auth/domain.crt /etc/docker/certs.d/localhost:5000/domain.crt
  # Create the credentials file, then start up the Docker registry
  - docker run --entrypoint htpasswd registry:2 -Bbn testuser testpassword > /home/travis/auth/htpasswd
  - docker run -d -p 5000:5000 --name registry -v /home/travis/auth:/home/travis/auth:Z -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/home/travis/auth/htpasswd -e REGISTRY_HTTP_TLS_CERTIFICATE=/home/travis/auth/domain.crt -e REGISTRY_HTTP_TLS_KEY=/home/travis/auth/domain.key registry:2

# Test Docker setup
  - docker ps --all
  - docker images
  - ls -alF /home/travis/auth
  - docker pull alpine
  - docker login localhost:5000 --username testuser --password testpassword
  - docker tag alpine localhost:5000/my-alpine
  - docker push localhost:5000/my-alpine
  - docker ps --all
  - docker images
  - docker rmi docker.io/alpine
  - docker rmi localhost:5000/my-alpine
  - docker pull localhost:5000/my-alpine
  - docker ps --all
  - docker images
  - docker rmi localhost:5000/my-alpine

  # mount yum repos to inherit injected mirrors from PAPR
  - docker run --net=host --privileged -v /etc/yum.repos.d:/etc/yum.repos.d.host:ro
    -v $PWD:/code registry.fedoraproject.org/fedora:26 sh -c
    "cp -fv /etc/yum.repos.d{.host/*.repo,} && /code/.papr.sh"
