# This build should fail if we're building with at least one non-amd64 platform
# either because we can't execute this test binary, or because it executed fine
# but returned an error
FROM alpine
RUN test `arch` = x86_64
