FROM busybox
# DO NOT TOUCH THIS UNLESS YOU KNOW WHAT YOU'RE DOING!
# renovatebot seems to want to clobber the image tag below. DO NOT LET IT DO SO.
COPY --from=quay.io/libpod/testimage:20221018 /home/podman/testimage-id /home/busyboxpodman/copied-testimage-id
