FROM alpine AS alias1
RUN echo "alias1" > /file1.txt

FROM alpine AS alias2
RUN echo "alias2" > /file2.txt

FROM alpine
COPY --from=alias1 /file1.txt /app/file1.txt
COPY --from=alias2 /file2.txt /app/file2.txt
RUN cat /app/file1.txt /app/file2.txt
