ARG PULLSPEC=alpine
ARG FIRST_STAGE=first-stage
ARG SECOND_STAGE=second-stage

FROM ${PULLSPEC} AS ${FIRST_STAGE}
RUN echo "first-stage content" > /output.txt

FROM ${FIRST_STAGE} AS ${SECOND_STAGE}
RUN echo "second-stage content" >> /output.txt

FROM alpine
COPY --from=second-stage /output.txt /app/output.txt
RUN cat /app/output.txt
