FROM alpine AS base
RUN echo "base" > /output.txt

FROM base AS transitive1
RUN echo "transitive1" >> /output.txt

FROM transitive1 AS transitive2
RUN echo "transitive2" >> /output.txt

FROM alpine
COPY --from=transitive2 /output.txt /app/output.txt
RUN cat /app/output.txt
