FROM alpine AS builder
RUN echo "building" > /build.txt

FROM alpine AS intermediate
RUN echo "intermediate" >> /build.txt

FROM alpine
COPY --from=intermediate /build.txt /app/build.txt
RUN echo "final"
