FROM alpine
COPY ./x/a.txt ./y/a.txt /no_parents/
COPY --parents ./x/a.txt ./y/a.txt /parents/
COPY --parents ./x/./y/* /parents_file_point/
COPY --parents ./x/./y/ /parents_dir_point/
run find /no_parents
run find /parents
run find /parents_file_point
run find /parents_dir_point
