FROM scratch as myname
COPY Dockerfile.name /

FROM scratch
COPY Dockerfile.index /

FROM scratch
COPY --from=myname /Dockerfile.name /Dockerfile.name
COPY --from=1 /Dockerfile.index /Dockerfile.index
